add_rules("mode.debug", "mode.release")

includes("common")
includes("assignment1")
includes("assignment2")
includes("assignment3")
includes("assignment4")
includes("assignment5")
includes("assignment6")
includes("assignment7")
includes("assignment8")
includes("assignment9")