target("raytracer1")
    set_kind("binary")
    add_deps("common")

    add_files("*.cpp", {includedirs="."})
    set_policy("build.warning", true)
    set_warnings("allextra")
    set_languages("c17", "cxx20")

task("test_raytracer1")
    set_category("plugin")
    on_run(function ()
        os.exec("xmake f -m release -c")
        os.exec("xmake -w raytracer1")
        local assets = path.join(os.scriptdir(), "assets")
        local imgs = path.join(os.scriptdir(), "imgs")
        os.exec("xmake r raytracer1 -input ".. assets .."/scene1_01.txt -size 200 200 -output ".. imgs .."/output1_01.tga -depth 9 10 ".. imgs .."/depth1_01.tga")
        os.exec("xmake r raytracer1 -input ".. assets .."/scene1_02.txt -size 200 200 -output ".. imgs .."/output1_02.tga -depth 8 12 ".. imgs .."/depth1_02.tga")
        os.exec("xmake r raytracer1 -input ".. assets .."/scene1_03.txt -size 200 200 -output ".. imgs .."/output1_03.tga -depth 8 12 ".. imgs .."/depth1_03.tga")
        os.exec("xmake r raytracer1 -input ".. assets .."/scene1_04.txt -size 200 200 -output ".. imgs .."/output1_04.tga -depth 12 17 ".. imgs .."/depth1_04.tga")
        os.exec("xmake r raytracer1 -input ".. assets .."/scene1_05.txt -size 200 200 -output ".. imgs .."/output1_05.tga -depth 14.5 19.5 ".. imgs .."/depth1_05.tga")
        os.exec("xmake r raytracer1 -input ".. assets .."/scene1_06.txt -size 200 200 -output ".. imgs .."/output1_06.tga -depth 3 7 ".. imgs .."/depth1_06.tga")
        os.exec("xmake r raytracer1 -input ".. assets .."/scene1_07.txt -size 200 200 -output ".. imgs .."/output1_07.tga -depth -2 2 ".. imgs .."/depth1_07.tga")
    end)
    set_menu {}