add_requires("opengl", "glu")
target("raytracer7")
    set_kind("binary")
    add_deps("common")
    add_packages("opengl", "glu")

    add_files("*.cpp", {includedirs="."})
    set_policy("build.warning", true)
    set_warnings("allextra")
    set_languages("c17", "cxx20")
    add_defines("_USE_MATH_DEFINES", "_HAS_STD_BYTE=0", "NOMINMAX")


task("raytracer7_scene7")
    set_category("plugin")
    on_run(function ()
        os.exec("xmake f -m release -c")
        os.exec("xmake -w raytracer7")
        local assets = path.join(os.scriptdir(), "assets")
        local imgs = path.join(os.scriptdir(), "imgs")
        
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 180 180 -output ".. imgs .."/output7_01.tga")
        
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_samples ".. imgs .."/samples7_01a.tga 20 -random_samples 4")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_samples ".. imgs .."/samples7_01b.tga 20 -uniform_samples 4")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_samples ".. imgs .."/samples7_01c.tga 20 -jittered_samples 4")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_samples ".. imgs .."/samples7_01d.tga 20 -random_samples 9")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_samples ".. imgs .."/samples7_01e.tga 20 -uniform_samples 9")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_samples ".. imgs .."/samples7_01f.tga 20 -jittered_samples 9")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_samples ".. imgs .."/samples7_01g.tga 20 -random_samples 36")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_samples ".. imgs .."/samples7_01h.tga 20 -uniform_samples 36")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_samples ".. imgs .."/samples7_01i.tga 20 -jittered_samples 36")
        
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_filter ".. imgs .."/filter7_01a.tga 20 -box_filter 0.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_filter ".. imgs .."/filter7_01b.tga 20 -tent_filter 0.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_filter ".. imgs .."/filter7_01c.tga 20 -gaussian_filter 0.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_filter ".. imgs .."/filter7_01d.tga 20 -box_filter 1.7")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_filter ".. imgs .."/filter7_01e.tga 20 -tent_filter 1.7")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_filter ".. imgs .."/filter7_01f.tga 20 -gaussian_filter 1.7")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_filter ".. imgs .."/filter7_01g.tga 20 -box_filter 2.3")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_filter ".. imgs .."/filter7_01h.tga 20 -tent_filter 2.3")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 9 9 -render_filter ".. imgs .."/filter7_01i.tga 20 -gaussian_filter 2.3")
        
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -output ".. imgs .."/output7_01_low_res.tga")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -render_samples ".. imgs .."/samples7_01a_low_res.tga 15 -random_samples 9")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -render_samples ".. imgs .."/samples7_01b_low_res.tga 15 -uniform_samples 9")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -render_samples ".. imgs .."/samples7_01c_low_res.tga 15 -jittered_samples 9")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -render_filter ".. imgs .."/filter7_01a_low_res.tga 15 -box_filter 0.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -render_filter ".. imgs .."/filter7_01b_low_res.tga 15 -tent_filter 1.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -render_filter ".. imgs .."/filter7_01c_low_res.tga 15 -gaussian_filter 1.0")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -output ".. imgs .."/output7_01a_low_res.tga -random_samples 9 -box_filter 0.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -output ".. imgs .."/output7_01b_low_res.tga -random_samples 9 -tent_filter 1.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -output ".. imgs .."/output7_01c_low_res.tga -random_samples 9 -gaussian_filter 1.0")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -output ".. imgs .."/output7_01d_low_res.tga -uniform_samples 9 -box_filter 0.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -output ".. imgs .."/output7_01e_low_res.tga -uniform_samples 9 -tent_filter 1.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -output ".. imgs .."/output7_01f_low_res.tga -uniform_samples 9 -gaussian_filter 1.0")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -output ".. imgs .."/output7_01g_low_res.tga -jittered_samples 9 -box_filter 0.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -output ".. imgs .."/output7_01h_low_res.tga -jittered_samples 9 -tent_filter 1.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_01_sphere_triangle.txt -size 12 12 -output ".. imgs .."/output7_01i_low_res.tga -jittered_samples 9 -gaussian_filter 1.0")
        
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 180 180 -output ".. imgs .."/output7_02.tga")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 9 9 -render_samples ".. imgs .."/samples7_02a.tga 20 -random_samples 16")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 9 9 -render_samples ".. imgs .."/samples7_02b.tga 20 -uniform_samples 16")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 9 9 -render_samples ".. imgs .."/samples7_02c.tga 20 -jittered_samples 16")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 9 9 -render_filter ".. imgs .."/filter7_02a.tga 20 -box_filter 0.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 9 9 -render_filter ".. imgs .."/filter7_02b.tga 20 -tent_filter 1.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 9 9 -render_filter ".. imgs .."/filter7_02c.tga 20 -gaussian_filter 0.6")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 180 180 -output ".. imgs .."/output7_02a.tga -random_samples 16 -box_filter 0.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 180 180 -output ".. imgs .."/output7_02b.tga -random_samples 16 -tent_filter 1.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 180 180 -output ".. imgs .."/output7_02c.tga -random_samples 16 -gaussian_filter 0.6")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 180 180 -output ".. imgs .."/output7_02d.tga -uniform_samples 16 -box_filter 0.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 180 180 -output ".. imgs .."/output7_02e.tga -uniform_samples 16 -tent_filter 1.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 180 180 -output ".. imgs .."/output7_02f.tga -uniform_samples 16 -gaussian_filter 0.6")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 180 180 -output ".. imgs .."/output7_02g.tga -jittered_samples 16 -box_filter 0.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 180 180 -output ".. imgs .."/output7_02h.tga -jittered_samples 16 -tent_filter 1.5")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_02_checkerboard.txt -size 180 180 -output ".. imgs .."/output7_02i.tga -jittered_samples 16 -gaussian_filter 0.6")
        
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_03_marble_vase.txt -size 200 200 -output ".. imgs .."/output7_03a.tga -grid 15 30 15 -shadows")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_03_marble_vase.txt -size 200 200 -output ".. imgs .."/output7_03b.tga -grid 15 30 15 -shadows -jittered_samples 4 -gaussian_filter 0.4")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_03_marble_vase.txt -size 200 200 -output ".. imgs .."/output7_03c.tga -grid 15 30 15 -shadows -jittered_samples 9 -gaussian_filter 0.4")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_03_marble_vase.txt -size 200 200 -output ".. imgs .."/output7_03d.tga -grid 15 30 15 -shadows -jittered_samples 36 -gaussian_filter 0.4")
        
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_04_6.837_logo.txt -size 400 200 -output ".. imgs .."/output7_04a.tga -shadows -shade_back -bounces 5 -weight 0.01 -grid 80 30 3")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_04_6.837_logo.txt -size 400 200 -output ".. imgs .."/output7_04b.tga -shadows -shade_back -bounces 5 -weight 0.01 -grid 80 30 3 -jittered_samples 9 -gaussian_filter 0.4")
        
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_05_glass_sphere.txt -size 300 300 -output ".. imgs .."/output7_05a.tga -shadows -shade_back -bounces 5 -weight 0.01 -grid 20 20 20")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_05_glass_sphere.txt -size 300 300 -output ".. imgs .."/output7_05b.tga -shadows -shade_back -bounces 5 -weight 0.01 -grid 20 20 20 -jittered_samples 4 -gaussian_filter 0.4")
        -- os.exec("xmake r raytracer7 -input ".. assets .."/scene7_05_glass_sphere.txt -size 300 300 -output ".. imgs .."/output7_05c.tga -shadows -shade_back -bounces 5 -weight 0.01 -grid 20 20 20 -jittered_samples 16 -gaussian_filter 0.4")
        
        os.exec("xmake r raytracer7 -input ".. assets .."/scene7_06_faceted_gem.txt -size 200 200 -output ".. imgs .."/output7_06a.tga -shadows -shade_back -bounces 5 -weight 0.01 -grid 20 20 20")
        os.exec("xmake r raytracer7 -input ".. assets .."/scene7_06_faceted_gem.txt -size 200 200 -output ".. imgs .."/output7_06b.tga -shadows -shade_back -bounces 5 -weight 0.01 -grid 20 20 20 -jittered_samples 9 -gaussian_filter 0.4")
    end)
    set_menu{}
